### ISSUE TITLE
jena parsing updates queries errors

### ISSUE THREAD

**Issue by gatemezing** [rvesse/sparql-query-bm#10]
Hi @rvesse, 
I am having an issue with updates queries containing ` WITH <graph> INSERT {} WHERE {} `.
I guess the error comes from jena parser!? I've tried to reproduce such error when using JENA CLI (`qparse --query <query.rq>`) and I receive the same parsing error. Is it related to the version of JENA? Is there any solution? TIA
<img width="694" alt="capture d ecran 2017-05-22 11 42 26" src="https://cloud.githubusercontent.com/assets/922883/26302252/ea14945c-3ee3-11e7-983b-9b2bf2324f6c.png">

**Comment by rvesse** [comment]
Queries and updates are distinct operations within both Jena and this tool. 

It is possible to benchmark updates but you have to be explicit that they are updates. This means of marking them as such in your mix files or using the appropriate operation type if interacting programmatically.

From the stack trace it appears you are using a mix file, therefore it should be sufficient to simply change the lines that referred to updates to be of the form:

    update	update.rq

Per https://sourceforge.net/p/sparql-query-bm/wiki/OperationMix/

**Comment by gatemezing** [comment]
Oops, I missed that one. Good catch. Thanks.
